### PR TITLE
add .mapReduce()

### PR DESCRIPTION
**Pull request by coderhaoxin**

### CODE REVIEW

**Comment by jonathanong** [comment]
what if i want to return the results immediately instead of through the collection?

**Comment by coderhaoxin** [comment]
the logic of `mongodb-native` is 

```js
    // If we wish for no verbosity
    if(options['verbose'] == null || !options['verbose']) {
      return handleCallback(callback, err, collection);
    }
    // Return stats as third set of values
    handleCallback(callback, err, collection, stats);
```

so, how about

```js
.mapReduce().map(map).reduce(reduce).verbose(true).then(function (stats) {})
.mapReduce().map(map).reduce(reduce).then(function (collection) {})

// or
.mapReduce().map(map).reduce(reduce).then(function (result) {
  // contain both `stats` and `collection` in result
  // result: { stats: stats, collection: collection }
  // or
  // just contain `collection` in `stats`
  // result: { processtime: ..., counts: ..., timing: ..., collection: collection }
})
```

**Comment by jonathanong** [comment]
ah. i didn't realize people actually looked at stats n stuff. i was thinking about inline: http://docs.mongodb.org/manual/reference/command/mapReduce/#output-inline

how do you use map/reduce? i've only ever used inline

**Comment by jonathanong** [comment]
i'm thinking of `.out(collection, [options])` for writing to a collection http://docs.mongodb.org/manual/reference/command/mapReduce/#output-to-a-collection-with-an-action, then `.inline()` for writing it directly out. or just make inline default.

**Comment by coderhaoxin** [comment]
:cry: yes, inline for most cases.

updated.

**Comment by jonathanong** [comment]
cool. looks good. the only thing i'd add is `.out('collectionName')`. is that supported?

**Comment by coderhaoxin** [comment]
yes, supported. maybe add a test is better.

**Comment by jonathanong** [comment]
32335bd109ae316605db1d06535a12cdb87d4594 thanks :D

**Pull request closed without merging**
